---
development:
  cloud_name: dukne3lhz
  api_key: <%= ENV['api_key'] %>
  api_secret: <%= ENV['api_secret'] %>
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: dukne3lhz
  api_key: <%= ENV['CLOUDINARY_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_file_support: true
  secure: true

test:
  cloud_name: dukne3lhz
  api_key: <%= ENV['api_key'] %>
  api_secret: <%= ENV['api_secret'] %>
  enhance_image_tag: true
  static_file_support: false
